### ISSUE TITLE
Parser to match a string

### ISSUE THREAD

**Issue by nburns** [kareman/FootlessParser#3]
Is there an easy way to construct a parser that matches more than one char in a row (a string)?

Say my language is made up of strings like: "foo 1" and "foo 2". What's the best way to construct a parser that matches the word "foo"?

Should I use the tokens function? https://github.com/kareman/FootlessParser/blob/master/source/StringParser.swift#L55

**Comment by kareman** [comment]
Hi and thanks for trying out Footlessparser. And yes, the tokens function will do the trick.
